apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: "dvonthenen/backend:latest"
          args:
            - "--advertised-ip=$(POD_IP)"
            - "--listen-ip=0.0.0.0"
            - "--listen-port=8080"
            - "--zipkin=http://zipkin.kube-system.svc.cluster.local:9411/api/v1/spans"
