apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: zipkin
  name: zipkin
  namespace: kube-system
spec:
  ports:
  - port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    k8s-app: zipkin
  sessionAffinity: None
  type: ClusterIP
